//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8793
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class TableSchema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal TableSchema() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarcodeFramework.TableSchema", typeof(TableSchema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE OHead
        ///(
        ///  OHeadGUID UNIQUEIDENTIFIER UNIQUE,
        ///  Num nvarchar(14),
        ///  DateCreated DATETIME,
        ///  Status int,
        ///  PRIMARY KEY(OHeadGUID)
        ///).
        /// </summary>
        internal static string OHead_SQL {
            get {
                return ResourceManager.GetString("OHead_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE OSpec
        ///(
        ///  OSpecGUID UNIQUEIDENTIFIER UNIQUE,
        ///  OHeadGUID UNIQUEIDENTIFIER,
        ///  DateCreated DATETIME,
        ///  ArtCode int,
        ///  Ean13 NVARCHAR(20),
        ///  Name  NVARCHAR(200), Qty int,
        ///  PRIMARY KEY(OSpecGUID)
        ///).
        /// </summary>
        internal static string OSpec_SQL {
            get {
                return ResourceManager.GetString("OSpec_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE SPREAN
        ///(
        ///  artcode int,
        ///  ean13 nvarchar(13),
        ///  names nvarchar(200),
        ///  primary key (ean13)
        ///).
        /// </summary>
        internal static string SprEan_SQL {
            get {
                return ResourceManager.GetString("SprEan_SQL", resourceCulture);
            }
        }
    }
}
